(defsystem "lem-rooms-client"
  :depends-on ()
  :serial t
  :components ((:file "utils")
               (:file "config")
               (:file "rooms-api")
               (:file "cursor")
               (:file "agent")
               (:File "agent-api")
               (:file "sign-in")
               (:file "user")
               (:file "room")
               (:file "buffer")
               (:file "management-buffer")
               (:file "main")))
